services:
  - type: web
    name: barbearia
    env: python
    pythonVersion: 3.12
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    disk:
      name: barbearia-db
      mountPath: /opt/render/project/src/data
      sizeGB: 1
